apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  username: bpmn_user
  password: bpmn_super_secret_password
  # Строка подключения, которую ожидает наш Rust-движок в переменной DATABASE_URL
  database-url: "postgres://bpmn_user:bpmn_super_secret_password@bpmn-db-rw:5432/bpmn_db"